VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "stockdata"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public ticker As String
Public yearchange As Double
Public percentchange As Double
Public totalstockvolume As Double
Public tradeDateOpen As Long
Public tradeDateClose As Long
Public yearOpen As Double
Public yearClose As Double
